/**
 * Email HTML templates.
 *
 * `buildLukeInquiryEmail` mirrors the structure of the original Python
 * `build_inquiry_email` in originalcalc/backend/main.py:272 — Luke is used to
 * that format. Two-column key/value tables for customer + project details,
 * line-item pricing breakdown, HUM finance summary with optimisation block
 * when it fired, prominent final-estimate box, repayment box, review flags.
 */

import type { ValidatedPayload } from "./submit";

const C = {
  text: "#333",
  bg: "#ffffff",
  navy: "#2c3e50",
  border: "#e0e0e0",
  rowAlt: "#f9f9f9",
  green: "#27ae60",
  greenSoft: "#f0f0f0",
  blue: "#2196F3",
  blueSoft: "#f0f8ff",
  orange: "#ff9800",
  orangeSoft: "#fff9e6",
  brand: "#FF6600",
  brandSoft: "#fff4ec",
  mute: "#666",
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function currency(n: number): string {
  return `$${n.toLocaleString("en-AU", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function titleCase(s: string): string {
  return s
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function timestamp(): string {
  const d = new Date();
  return d.toLocaleString("en-AU", {
    timeZone: "Australia/Melbourne",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
}

// =============================================================================
// Inquiry email to Luke (eligible path)
// =============================================================================

export function buildLukeInquiryEmail(payload: ValidatedPayload): string {
  const { customer, project, estimate, plans, photos } = payload;

  const sectionsHtml =
    project.areaMethod === "sections" && project.areaSections?.length
      ? `<tr><td class="lbl">Section breakdown:</td><td>${project.areaSections
          .map(
            (s, i) =>
              `Section ${i + 1}: ${s.length}m × ${s.width}m = ${(s.length * s.width).toFixed(2)}m²`,
          )
          .join("<br/>")}</td></tr>`
      : "";

  const areaDisplay =
    project.areaMethod === "plans"
      ? "<em>To be derived from uploaded plans</em>"
      : `${project.areaSqm}m²`;

  const pricingHtml = estimate ? buildPricingSection(estimate) : "";
  const attachmentsHtml = buildAttachmentsSection(plans, photos);

  return wrap(
    `Driveway Estimate Inquiry`,
    `
    <div class="section">
      <h3>Customer Details</h3>
      <table class="kv">
        <tr><td class="lbl">Name:</td><td>${escapeHtml(customer.name)}</td></tr>
        <tr><td class="lbl">Phone:</td><td><a href="tel:${escapeHtml(customer.phone)}">${escapeHtml(customer.phone)}</a></td></tr>
        <tr><td class="lbl">Email:</td><td><a href="mailto:${escapeHtml(customer.email)}">${escapeHtml(customer.email)}</a></td></tr>
        <tr><td class="lbl">Suburb/Postcode:</td><td>${escapeHtml(customer.suburb)}</td></tr>
      </table>
    </div>

    <div class="section">
      <h3>Project Details</h3>
      <table class="kv">
        <tr><td class="lbl">Finish:</td><td>${titleCase(project.finish)}</td></tr>
        <tr><td class="lbl">Area:</td><td>${areaDisplay}</td></tr>
        <tr><td class="lbl">Measurement Source:</td><td>${titleCase(project.areaMethod)}</td></tr>
        ${sectionsHtml}
        <tr><td class="lbl">Existing Surface Removal:</td><td>${project.hasRemoval ? "Yes" : "No"}</td></tr>
        <tr><td class="lbl">Slope:</td><td>${titleCase(project.slope)}</td></tr>
        <tr><td class="lbl">Drainage:</td><td>${titleCase(project.drainage)}${project.stripDrainLengthM ? ` (≈ ${project.stripDrainLengthM}m strip drain)` : ""}</td></tr>
      </table>
    </div>

    ${pricingHtml}

    ${attachmentsHtml}

    <div class="section">
      <p style="color:${C.mute};font-size:12px;">
        Generated by the Smooth Concrete calculator at ${timestamp()}.<br/>
        Reply directly to this email to reach the customer
        (${escapeHtml(customer.email)}).
      </p>
    </div>
    `,
  );
}

// =============================================================================
// Partial-lead alert — first page only (customer dropped off before finishing)
// =============================================================================

export function buildPartialLeadEmail(
  customer: { name: string; phone: string; email: string; suburb: string },
  sourceUrl?: string,
): string {
  return wrap(
    `New Lead — First Page Only`,
    `
    <div class="section">
      <p style="background:${C.orangeSoft};padding:12px;border-left:4px solid ${C.orange};margin:0 0 16px 0;">
        <strong>⚠️ This customer entered their contact details but has not
        completed the full quote yet.</strong><br/>
        Worth reaching out in case they drop off. If they finish, the full
        estimate email will follow separately.
      </p>
      <h3>Customer Details</h3>
      <table class="kv">
        <tr><td class="lbl">Name:</td><td>${escapeHtml(customer.name)}</td></tr>
        <tr><td class="lbl">Phone:</td><td><a href="tel:${escapeHtml(customer.phone)}">${escapeHtml(customer.phone)}</a></td></tr>
        <tr><td class="lbl">Email:</td><td><a href="mailto:${escapeHtml(customer.email)}">${escapeHtml(customer.email)}</a></td></tr>
        <tr><td class="lbl">Suburb/Postcode:</td><td>${escapeHtml(customer.suburb)}</td></tr>
      </table>
    </div>

    <div class="section">
      <p style="color:${C.mute};font-size:12px;">
        Captured by the Smooth Concrete calculator at ${timestamp()}${sourceUrl ? ` from ${escapeHtml(sourceUrl)}` : ""}.<br/>
        Reply directly to this email to reach the customer
        (${escapeHtml(customer.email)}).
      </p>
    </div>
    `,
  );
}

function buildAttachmentsSection(
  plans: { url: string; filename: string; contentType: string; size: number }[],
  photos: { url: string; filename: string; contentType: string; size: number }[],
): string {
  if (plans.length === 0 && photos.length === 0) return "";

  const renderItem = (
    f: { url: string; filename: string; contentType: string },
  ) => {
    const isImage = f.contentType.startsWith("image/");
    return `
      <div style="display:inline-block;margin:6px 8px 6px 0;vertical-align:top;text-align:center;">
        <a href="${escapeHtml(f.url)}" target="_blank" rel="noopener" style="text-decoration:none;color:${C.navy};">
          ${
            isImage
              ? `<img src="${escapeHtml(f.url)}" alt="${escapeHtml(f.filename)}" style="display:block;width:140px;height:140px;object-fit:cover;border-radius:6px;border:1px solid ${C.border};" />`
              : `<div style="width:140px;height:140px;background:${C.rowAlt};border:1px solid ${C.border};border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:32px;">📄</div>`
          }
          <div style="font-size:11px;color:${C.mute};margin-top:4px;max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${escapeHtml(f.filename)}</div>
        </a>
      </div>
    `;
  };

  return `
    ${
      plans.length > 0
        ? `<div class="section">
             <h3>Plans / Site Drawings</h3>
             ${plans.map(renderItem).join("")}
           </div>`
        : ""
    }
    ${
      photos.length > 0
        ? `<div class="section">
             <h3>Photos</h3>
             ${photos.map(renderItem).join("")}
           </div>`
        : ""
    }
  `;
}

function buildPricingSection(
  estimate: NonNullable<ValidatedPayload["estimate"]>,
): string {
  const lineItems = estimate.lineItems
    .map(
      (li) => `
      <tr>
        <td>${escapeHtml(li.description)}</td>
        <td style="text-align:right;">${currency(li.amount)}</td>
      </tr>`,
    )
    .join("");

  const optimizationHtml =
    estimate.optimizationOccurred && estimate.optimizationDetails
      ? `<div style="background:${C.blueSoft};padding:12px;border-left:4px solid ${C.blue};margin:10px 0;">
           <strong>✓ HUM Bracket Optimisation Applied</strong><br/>
           Original bracket: ${escapeHtml(estimate.originalBracket.rangeDesc)} @ ${estimate.originalBracket.feePercent}%<br/>
           Optimised bracket: ${escapeHtml(estimate.optimizedBracket.rangeDesc)} @ ${estimate.optimizedBracket.feePercent}%<br/>
           Discount applied: ${currency(estimate.discountApplied)}<br/>
           Merchant fee savings: ${currency(estimate.optimizationDetails.feeSavings)}<br/>
           Net benefit: ${currency(estimate.optimizationDetails.netBenefit)}
         </div>`
      : "";

  const flagsHtml =
    estimate.reviewFlags.length > 0
      ? `<div class="section">
           <h3>Review Flags</h3>
           <ul>${estimate.reviewFlags.map((f) => `<li>${escapeHtml(f)}</li>`).join("")}</ul>
         </div>`
      : "";

  return `
    <div class="section">
      <h3>Pricing Breakdown</h3>
      <table class="kv">
        ${lineItems}
        <tr style="font-weight:700;background:${C.rowAlt};">
          <td>Subtotal (ex GST, ex finance)</td>
          <td style="text-align:right;">${currency(estimate.originalSubtotal)}</td>
        </tr>
      </table>
    </div>

    <div class="section">
      <h3>HUM Finance Calculation</h3>
      <table class="kv">
        <tr><td class="lbl">Original HUM Bracket:</td><td>${escapeHtml(estimate.originalBracket.rangeDesc)} @ ${estimate.originalBracket.feePercent}%</td></tr>
        <tr><td class="lbl">Original Repayment Terms:</td><td>${estimate.originalBracket.fortnights} fortnights (${estimate.originalBracket.fortnights * 2} weeks)</td></tr>
      </table>

      ${optimizationHtml}

      <table class="kv">
        <tr><td class="lbl">Final HUM Bracket:</td><td>${escapeHtml(estimate.optimizedBracket.rangeDesc)} @ ${estimate.optimizedBracket.feePercent}%</td></tr>
        <tr><td class="lbl">Finance-Adjusted (ex GST):</td><td style="text-align:right;">${currency(estimate.financeAdjustedExGst)}</td></tr>
        <tr><td class="lbl">GST (10%):</td><td style="text-align:right;">${currency(estimate.gstAmount)}</td></tr>
      </table>

      <div style="background:${C.greenSoft};padding:15px;margin:10px 0;border-left:4px solid ${C.green};">
        <div>Final Estimate (inc GST)</div>
        <div style="font-size:28px;font-weight:700;color:${C.green};">${currency(estimate.finalIncGst)}</div>
      </div>
    </div>

    <div class="section">
      <h3>Customer-Facing Repayment</h3>
      <div style="background:${C.orangeSoft};padding:12px;border-left:4px solid ${C.orange};">
        <p style="margin:0;"><strong>Weekly Repayment Amount</strong></p>
        <div style="font-size:20px;font-weight:700;color:${C.orange};">${currency(estimate.repayment.weekly)}/week</div>
        <p style="margin:8px 0 0 0;font-size:12px;">
          ${estimate.repayment.fortnights} fortnights (${estimate.repayment.termWeeks} weeks)<br/>
          Fortnightly: ${currency(estimate.repayment.fortnightly)}/fn
        </p>
      </div>
    </div>

    ${flagsHtml}
  `;
}

// =============================================================================
// Shared shell — wraps body content in the same HTML chrome the original
// inquiry email used (navy header, white card, key-value tables).
// =============================================================================

function wrap(title: string, bodyHtml: string): string {
  return `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: Arial, sans-serif; color: ${C.text}; background: ${C.bg}; margin: 0; padding: 0; }
      .container { max-width: 700px; margin: 0 auto; padding: 20px; }
      .header { background: ${C.navy}; color: white; padding: 20px; border-radius: 4px; margin-bottom: 20px; }
      .header h2 { margin: 0; font-size: 22px; }
      .header .ts { font-size: 12px; opacity: 0.85; margin-top: 4px; }
      .section { margin-bottom: 20px; }
      .section h3 { color: ${C.navy}; border-bottom: 2px solid ${C.border}; padding-bottom: 8px; margin-bottom: 10px; font-size: 16px; }
      table { width: 100%; border-collapse: collapse; }
      table.kv td { padding: 8px; border-bottom: 1px solid ${C.border}; font-size: 14px; }
      table.kv td.lbl { font-weight: 600; width: 40%; }
      a { color: ${C.navy}; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h2>${escapeHtml(title)}</h2>
        <div class="ts">Received ${timestamp()}</div>
      </div>
      ${bodyHtml}
    </div>
  </body>
</html>`.trim();
}
